name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: |
          go install
          go install golang.org/x/lint/golint@latest

      - name: Build
        run: go build -v ./...

      - name: Run vet & lint
        run: |
          go vet .
          golint .

      - name: Test
        run: go test -v ./...

      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results
          path: TestResults.json
